# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get & Install Test Studio Runtime
        shell: pwsh
        run: |
             $filepath = "TestStudio_Runtime.msi"
             $r = Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1QYdNQYTls9oqLB6QCR1f9DG_ZxTJstDn" -SessionVariable $googleDriveSession
             $s = $r.Content -match 'action=\"(.*?)\"'
             Add-Type -AssemblyName System.Web
             $d = [System.Web.HttpUtility]::HtmlDecode($matches[1])
             echo $d
             Invoke-WebRequest -Uri $d -WebSession $googleDriveSession -Method Post -OutFile $filepath
             $log = "install.log" 
             $procMain = Start-Process "msiexec" "/i `"$filepath`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
             $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru 
             $procMain.WaitForExit() 
             $procLog.Kill()
      - name: Run Test List
        shell: pwsh
        run: |
            "C:\Program Files (x86)\Progress\Test Studio\Bin\ArtOfTest.Runner.exe" list="${{ github.workspace }}\TestStudioProject1\TestLists\TestList1.aiilist" result="TestStudio" junit
             
            
          
            
